apiVersion: v1
kind: Namespace
metadata:
  name: argocd
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: application-set
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - git:
      repoURL: https://github.com/evan-hines-js/homelab.git
      revision: HEAD
      directories:
      - path: applications/**/*/*
  template:
    metadata:
      name: '{{.path.basenameNormalized}}'
      namespace: argocd
    spec:
      project: "default"
      source:
        repoURL: https://github.com/evan-hines-js/homelab.git
        targetRevision: HEAD
        path: '{{.path.path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{index .path.segments 2}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true